eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8086
spring:
  application:
    name: service-live2d

jfm:
  config:
    static-file-path: C:\Users\admin\Desktop\static-file